services:
  accounts:
    image: "accounts"
    ports:
      - "8080:8080"
    container_name: "accounts_ms"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - eazybank
networks:
  eazybank:
    driver: "bridge"