spring:
  application:
    name: accounts
  profiles:
    active: "qa"
  datasource:
    url: jdbc:h2:mem:testdb # jdbc:mysql://localhost:3306/accountsdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
#  sql:
#    init:
#      mode: always

  config:
    import: "optional:configserver:http://localhost:8071"
#  cloud:
#    stream:
#      bindings:
#        sendCommunication-out-0:
#          destination: send-communication
#
#  rabbitmq:
#    port: 5672
#    host: "localhost"
#    username: "guest"
#    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
  endpoint:
    shutdown:
      access: unrestricted

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: "http://localhost:8070/eureka"

info:
  app:
    name: "accounts"
    description: "App to manage accounts"
    version: "0.0.1"