name: test
on: workflow_dispatch
jobs:
  placeholder:
    runs-on: ubuntu-latest
    steps:
      - name: "Placeholder for future workflows"
        run: echo " I'm just holding place for future workflows :) "